name: wash_and_dry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  crypto: ^3.0.7
  bcrypt: ^1.2.0
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  google_sign_in: ^6.2.1
  get: ^4.7.3
  google_fonts: ^8.0.0
  firebase_app_check: ^0.4.1+4
  flutter_secure_storage: ^10.0.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  geocoding: ^4.0.0
  geolocator: ^12.0.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.14.0
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  font_awesome_flutter: ^10.12.0
  firebase_messaging: 16.4.1
  flutter_local_notifications: ^18.0.1
  calendar_date_picker2: ^3.0.0
  image_cropper: ^12.2.1
  flutter_compass: ^0.8.1
  gal: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

 
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
